# /.github/workflows/main.yml
name: Trigger Netlify Build
on:
  schedule:
    # Every friday at midnight
    - cron: '0 0 * * 5'
jobs:
  build:
    name: Netlify build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/60016672d09d07cb04fb5904
